# Generated by Django 2.2.3 on 2019-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_auto_20190809_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='body2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
