# Generated by Django 2.2.3 on 2019-08-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0005_remove_prop_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='user',
        ),
    ]
