# Generated by Django 2.2.3 on 2019-08-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_prop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='image',
        ),
    ]
