# Generated by Django 2.2.3 on 2019-08-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0008_remove_prop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
