# Generated by Django 2.2.3 on 2019-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Place',
        ),
    ]
