# Generated by Django 2.2.3 on 2019-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20190722_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
