# Generated by Django 2.2.3 on 2019-08-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20190809_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='author',
        ),
        migrations.RemoveField(
            model_name='place',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='place',
            name='like',
        ),
    ]
