# Generated by Django 2.2.3 on 2019-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20190809_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='user', to='place.Place'),
        ),
    ]
