# Generated by Django 2.2.3 on 2019-08-09 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0005_place_like_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='like_posts',
        ),
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
