# Generated by Django 2.2.3 on 2019-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='time',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
