# Generated by Django 2.2.3 on 2019-08-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_place_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
