# Generated by Django 2.2.3 on 2019-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='제목:')),
                ('content', models.TextField(null=True, verbose_name='내용:')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=100, verbose_name='링크주소:')),
            ],
        ),
    ]
