# Generated by Django 2.2.3 on 2019-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_edit', '0004_auto_20190808_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
