# Generated by Django 2.2.3 on 2019-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_edit', '0005_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
